language: node_js
node_js:
  - 5

install:
  - npm install
  - npm install --quiet -g karma
  - npm install --quiet -g protractor
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - webdriver-manager update
  - protractor config/protractor-conf.js --browser=firefox
